services:
  mysql:
    image: mysql:8.0
    container_name: pricewatch-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: pricewatch
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: pricewatch-redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pricewatch-app
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql:3306/pricewatch?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8
      DB_USERNAME: root
      DB_PASSWORD: root1234
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: pricewatch-secret-key-pricewatch-secret-key

volumes:
  mysql-data:
