services:
  mysql:
    image: mysql:8.0
    container_name: pricewatch-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: pricewatch
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: pricewatch-redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: pricewatch-elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pricewatch-app
    depends_on:
      - mysql
      - redis
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql:3306/pricewatch?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8
      DB_USERNAME: root
      DB_PASSWORD: root1234
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      ELASTICSEARCH_URIS: http://elasticsearch:9200
      PRODUCT_SEARCH_ES_ENABLED: true
      JWT_SECRET: pricewatch-secret-key-pricewatch-secret-key

volumes:
  mysql-data:
